import { inter } from "./ui/fonts";
import NavBar from "./ui/navbar";
import Footer from "./ui/footer";
import "./globals.css";
import Context from "./context";

export const revalidate = 60

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
          <Context>
            <NavBar />
            {children}
            <Footer />
          </Context>
        </body>
    </html>
  )
}
