import { inter } from '@/app/ui/fonts';
import NavBar from "./ui/navbar";
import "./globals.css";
import Context from './context';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Context>
        <body className={inter.className}>
        <NavBar />
          {children}
        </body>
      </Context>
    </html>
  );
}
